### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by SuperQAxClub** [moifort/homebridge-mi-led-desk-lamp#2]
Hi, I'm trying to setup homebridge for my Xiaomi LED desk lamp, after config the hombridge and try to launch homebridge, I get the following errors:

```bash
[root@localhost ~]# homebridge
[9/13/2019, 12:09:56 PM] Loaded config.json with 1 accessories and 1 platforms.
[9/13/2019, 12:09:56 PM] ---
[9/13/2019, 12:09:56 PM] Plugin /usr/lib/node_modules/homebridge-config-ui-x does not contain a package.json.
[9/13/2019, 12:09:56 PM] ====================
[9/13/2019, 12:09:56 PM] ERROR LOADING PLUGIN homebridge-mi-led-desk-lamp:
[9/13/2019, 12:09:56 PM] /usr/lib/node_modules/homebridge-mi-led-desk-lamp/index.js:37
    async getLamp() {
          ^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:72:23)
[9/13/2019, 12:09:56 PM] ====================
[9/13/2019, 12:09:56 PM] No plugins found. See the README for information on installing plugins.
[9/13/2019, 12:09:56 PM] Loading 1 platforms...
[9/13/2019, 12:09:56 PM] TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:120:11)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
[9/13/2019, 12:09:56 PM] Got SIGTERM, shutting down Homebridge...

```

My config.json
```javascript
{
  "bridge": {
    "name": "Desk Lamp",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  
  "description": "Xiaomi LED Desk Lamp.",
  "ports": {
    "start": 52100,
    "end": 52150,
    "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
  },
  "accessories": [
    {
        "accessory": "mi-led-desk-lamp",
        "name": "My desk lamp",
        "ip": "192.168.0.23",
        "token": "**CENSORED**"
    }
  ],

  "platforms": [
    {
      
    }
  ]
}
```

**Comment by moifort** [comment]
You should use a version of node >= 7.6. I use async/await who are feature of ES6.
