### ISSUE TITLE
he requested accessory 'mi-led-desk-lamp' was not registered by any plugin.

### ISSUE THREAD

**Issue by helloworlde** [moifort/homebridge-mi-led-desk-lamp#4]
Hi, I had try to use this plugin, but found the error like this:

```
[12/8/2019, 4:38:31 AM] Loaded config.json with 1 accessories and 0 platforms.
[12/8/2019, 4:38:31 AM] ---
[12/8/2019, 4:38:31 AM] No plugins found. See the README for information on installing plugins.
[12/8/2019, 4:38:31 AM] Loading 0 platforms...
[12/8/2019, 4:38:31 AM] Loading 1 accessories...
[12/8/2019, 4:38:31 AM] Error: The requested accessory 'mi-led-desk-lamp' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[12/8/2019, 4:38:31 AM] Got SIGTERM, shutting down Homebridge...
```

my config is :

```json
{
  "bridge": {
    "name": "Homebridge",
    "username": "11:22:33:44:55:66",
    "port": 51826,
    "pin": "031-45-154"
  },
   "accessories": [
    {
    "accessory": "mi-led-desk-lamp",
    "name": "My desk lamp",
    "ip": "192.168.199.6",
    "token": "TOKEN"
    }
  ],
  "platforms": []
}
```

I'm new player in nodejs, could you please help find how to fix this? Thanks very much.

**Comment by helloworlde** [comment]
Finally, I found my homebridge is run in docker, but i install in host.
