### ISSUE TITLE
Handshake timeout

### ISSUE THREAD

**Issue by Jafalex** [moifort/homebridge-mi-led-desk-lamp#7]
Salut,

Ce plug-in est-il toujours mis à jour ?

Je viens de l'installer pour la premiere fois et je n'arrive pas à me débarrasser de l'erreur suivante:

```
[9/29/2020, 11:12:01 AM] [Office lamp] Device not connected Error: Could not connect to device, handshake timeout
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-mi-led-desk-lamp/node_modules/miio/lib/network.js:427:17)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout',
  device: null
}
[9/29/2020, 11:12:01 AM] [Office lamp] TypeError: Cannot read property 'on' of undefined
    at MiLedDesklamp.listenLampState (/homebridge/node_modules/homebridge-mi-led-desk-lamp/index.js:59:16)
```

Any idea?

**Comment by Rpickp** [comment]
Edit: I found out that the IP address of the lamp had changed on my router. I updated it on Hoobs and it works perfectly now. I set the IP to be fixed for the lamp to prevent this issue in the future. 

I have the same issue:
[Desk Lamp] Device not connected Error: Could not connect to device, handshake timeout
    at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/miio/lib/network.js:427:17)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'timeout',
  device: null
}

**Comment by EnixCoda** [comment]
The error is raised from `miio`, a dependency of this project.

**Comment by EnixCoda** [comment]
If you are using devices in another subnet, you should read [this issue](https://github.com/aholstenson/miio/issues/282).

Update: I finally managed to make it work after setting up proper NAT in my router.

**Comment by Jafalex** [comment]
> If you are using devices in another subnet, you should read [this issue](https://github.com/aholstenson/miio/issues/92).
> 
> Update: I finally managed to make it work after setting up proper NAT in my router.

Yup, the lamp sits in a subnet dedicated to IoT devices, whereas the homebridge docker container runs in the "server" subnet.
Sorry I don't see the hint on that thread you linked to. any chance you could guide me a bit further on the solution here please? Thanks heaps

**Comment by EnixCoda** [comment]
@Jafalex Sorry the link was not correct. I've updated it.

**Comment by Jafalex** [comment]
Thanks :-) That sounds like a headache in UniFi world, but I'll dig into it.
